### ISSUE TITLE
Test for command history hangs forever on Azure (and possibly others)

### ISSUE THREAD

**Issue by MrBatschner** [gardenlinux/gardenlinux#1235]
**What happened:**

Running the platform tests on Azure (client logs in with user `azureuser`), the test `server/test/test_history.py` hangs forever at this line: https://github.com/gardenlinux/gardenlinux/blob/87d76e9db557a8dab92cbf6b3b6feb7017dd7f57/tests/helper/utils.py#L97

Reason will probably be that `su - root` is waiting for a password that it will never get.

**How to reproduce it**:

Run the platform tests for Azure with the following config:

```
azure:
    location: westeurope
    subscription: <redacted>
    image: file:///gardenlinux/.build/azure-gardener-amd64-today-local.vhd
    ssh:
      ssh_key_filepath: /config/id_rsa_gardenlinux_test
    keep_running: false
    features:
      - base
      - server
      - cloud
      - gardener
      - azure
```
 
**Environment:**

Platform tests were run with the code from commit 6f7d6513c4f34b260f5c32fbbcec1c5e0c94e8cc.
