### ISSUE TITLE
Upload build artefacts to AWS CN as well

### ISSUE THREAD

**Issue by MrBatschner** [gardenlinux/gardenlinux#2121]
**Why is this needed**:

Currently, all build artefacts are uploaded to the `github-releases` S3 bucket on AWS `eu-central-1`. From here, they are taken to release them as images on major cloud platforms.

For those cloud platforms in China behind the great firewall, this creates problems with the release pipeline. Right now, the release pipeline takes the artefacts from AWS `eu-central-1` and replicates it to the `gardenlinux` bucket in `cn-northwest-1` of the AWS CN partition from which it will be imported. Unfortunately, this [replication](https://github.com/gardenlinux/glci/blob/main/replicate.py) is unstable and runs into many timeouts preventing us from releasing swiftly.

**What would you like to be added**:

The build artefacts that get uploaded to S3 in [this GH action](https://github.com/gardenlinux/gardenlinux/blob/main/.github/workflows/upload_to_s3.yml) should also get uploaded to S3 on AWS CN. Not all artefacts need to be replicated, right now only those for `aws`, `openstack` and `openstackbaremetal` must be replicated. To identify these images, the release manifest should be amended by a new fields:

Current:

```yaml
paths:
- name: openstack-gardener_prod-amd64-1443.5-bfb687a7/openstack-gardener_prod-amd64-1443.5-bfb687a7.manifest
  s3_bucket_name: gardenlinux-github-releases
  s3_key: objects/openstack-gardener_prod-amd64-1443.5-bfb687a7/openstack-gardener_prod-amd64-1443.5-bfb687a7.manifest
  suffix: .manifest
- ...
```

New:

```yaml
paths:
- name: openstack-gardener_prod-amd64-1443.5-bfb687a7/openstack-gardener_prod-amd64-1443.5-bfb687a7.manifest
  s3_bucket_name: gardenlinux-github-releases
  s3_bucket_name_cn: gardenlinux
  s3_key: objects/openstack-gardener_prod-amd64-1443.5-bfb687a7/openstack-gardener_prod-amd64-1443.5-bfb687a7.manifest
  suffix: .manifest
- ...
```

With this updated structure, glci's replication/import job can be modified to always take the image artefacts from an S3 bucket in China to import to Cloud-Platform regions in China (for those cloud platforms that support image import from an S3 URL) or even removed entirely (needs to be evaluated in glci).
