### ISSUE TITLE
better download links to current and historic patch and nightly images

### ISSUE THREAD

**Issue by yeoldegrove** [gardenlinux/gardenlinux#2427]
**What would you like to be added**:

In https://github.com/gardenlinux/gardenlinux/blob/main/README.md there is a download section that mentions a rough overview where to get the images for the different use cases. This could be enhanced.

Patch releases have download links but there is no easy machine readable way to get those. It would be great to have a way to list/retrieve those download links.

Currently there is no easy way to find download links for nightly cloud images and container images. It would be great if this information would be visible somewhere.

##### cloud images

- github releases with download links only exist for patch releases
  - these are not very "machine readable"
- GLRD contains git commits that could be used to get images from our S3 release bucket
  - ideas:
    - Would/Could have to be connected to actual images somehow
      - e.g. via adding fields to the GLRD schema for images or downloadable artefacts

##### container images

- the current nightly build is tagged `nightly` but historic nightlies are not tagged in any way
  - https://github.com/gardenlinux/gardenlinux/pkgs/container/gardenlinux
    - ideas: 
      - same naming scheme as in GLRD could be added as additional tag, e.g. `nightly-1312.0`
      - same naming scheme could also be added to `patch` releases, e.g. `patch-1312.0`
      - GLRD schema extension for container images or downloadable artefacts

**Why is this needed**:

- As a developer I want to have an easy way of testing the latest/nightly version of Garden Linux or run/digest two patch/nightly versions easily.
- As a User I want to have an overview on where to download the latest/nightly and current and older patch releases of Garden Linux. This should be reflected in https://github.com/gardenlinux/gardenlinux/blob/main/README.md.

**Comment by yeoldegrove** [comment]
@pnpavlov Maybe different approaches than additional GLRD fields could also be an option but this is the first thing that struck my mind as a possible solution.

**Comment by yeoldegrove** [comment]
https://github.com/gardenlinux/glrd/releases/tag/v3.1.0 now includes flavors and their download links for manifests,  images and OCI.

```
❯ podman run --pull=always -itq --rm ghcr.io/gardenlinux/glrd:v3.1.0 "glrd --latest --output-format yaml"
releases:
- name: patch-1592.6
  type: patch
  version:
    major: 1592
    minor: 6
  lifecycle:
    released:
      isodate: '2025-02-19'
      timestamp: 1739951325
    eol:
      isodate: '2025-08-12'
      timestamp: 1754956800
  git:
    commit: cb05e11f0481b72d0a30da3662295315b220a436
    commit_short: cb05e11f
  github:
    release: https://github.com/gardenlinux/gardenlinux/releases/tag/1592.6
  flavors:
    ali-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/ali-gardener_prod-amd64-1592.6-cb05e11f/ali-gardener_prod-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/ali-gardener_prod-amd64-1592.6-cb05e11f/ali-gardener_prod-amd64-1592.6-cb05e11f.qcow2
    ali-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/ali-gardener_prod-arm64-1592.6-cb05e11f/ali-gardener_prod-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/ali-gardener_prod-arm64-1592.6-cb05e11f/ali-gardener_prod-arm64-1592.6-cb05e11f.qcow2
    aws-gardener_persistence_prod_readonly_secureboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f/aws-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f/aws-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f.raw
    aws-gardener_persistence_prod_readonly_secureboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f/aws-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f/aws-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f.raw
    aws-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod-amd64-1592.6-cb05e11f/aws-gardener_prod-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod-amd64-1592.6-cb05e11f/aws-gardener_prod-amd64-1592.6-cb05e11f.raw
    aws-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod-arm64-1592.6-cb05e11f/aws-gardener_prod-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod-arm64-1592.6-cb05e11f/aws-gardener_prod-arm64-1592.6-cb05e11f.raw
    aws-gardener_prod_readonly_secureboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f/aws-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f/aws-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f.raw
    aws-gardener_prod_readonly_secureboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f/aws-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f/aws-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f.raw
    aws-gardener_prod_secureboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_secureboot-amd64-1592.6-cb05e11f/aws-gardener_prod_secureboot-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_secureboot-amd64-1592.6-cb05e11f/aws-gardener_prod_secureboot-amd64-1592.6-cb05e11f.raw
    aws-gardener_prod_secureboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_secureboot-arm64-1592.6-cb05e11f/aws-gardener_prod_secureboot-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_secureboot-arm64-1592.6-cb05e11f/aws-gardener_prod_secureboot-arm64-1592.6-cb05e11f.raw
    azure-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod-amd64-1592.6-cb05e11f/azure-gardener_prod-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod-amd64-1592.6-cb05e11f/azure-gardener_prod-amd64-1592.6-cb05e11f.vhd
    azure-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod-arm64-1592.6-cb05e11f/azure-gardener_prod-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod-arm64-1592.6-cb05e11f/azure-gardener_prod-arm64-1592.6-cb05e11f.vhd
    gcp-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod-amd64-1592.6-cb05e11f/gcp-gardener_prod-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod-amd64-1592.6-cb05e11f/gcp-gardener_prod-amd64-1592.6-cb05e11f.gcpimage.tar.gz
    gcp-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod-arm64-1592.6-cb05e11f/gcp-gardener_prod-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod-arm64-1592.6-cb05e11f/gcp-gardener_prod-arm64-1592.6-cb05e11f.gcpimage.tar.gz
    gdch-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gdch-gardener_prod-amd64-1592.6-cb05e11f/gdch-gardener_prod-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gdch-gardener_prod-amd64-1592.6-cb05e11f/gdch-gardener_prod-amd64-1592.6-cb05e11f.gcpimage.tar.gz
    gdch-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gdch-gardener_prod-arm64-1592.6-cb05e11f/gdch-gardener_prod-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gdch-gardener_prod-arm64-1592.6-cb05e11f/gdch-gardener_prod-arm64-1592.6-cb05e11f.gcpimage.tar.gz
    kvm-gardener_persistence_prod_readonly_secureboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f/kvm-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f/kvm-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f.raw
    kvm-gardener_persistence_prod_readonly_secureboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f/kvm-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f/kvm-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f.raw
    kvm-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod-amd64-1592.6-cb05e11f/kvm-gardener_prod-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod-amd64-1592.6-cb05e11f/kvm-gardener_prod-amd64-1592.6-cb05e11f.raw
    kvm-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod-arm64-1592.6-cb05e11f/kvm-gardener_prod-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod-arm64-1592.6-cb05e11f/kvm-gardener_prod-arm64-1592.6-cb05e11f.raw
    kvm-gardener_prod_readonly_secureboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f/kvm-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f/kvm-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f.raw
    kvm-gardener_prod_readonly_secureboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f/kvm-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f/kvm-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f.raw
    kvm-gardener_prod_secureboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_secureboot-amd64-1592.6-cb05e11f/kvm-gardener_prod_secureboot-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_secureboot-amd64-1592.6-cb05e11f/kvm-gardener_prod_secureboot-amd64-1592.6-cb05e11f.raw
    kvm-gardener_prod_secureboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_secureboot-arm64-1592.6-cb05e11f/kvm-gardener_prod_secureboot-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_secureboot-arm64-1592.6-cb05e11f/kvm-gardener_prod_secureboot-arm64-1592.6-cb05e11f.raw
    metal-gardener_persistence_prod_readonly_secureboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f/metal-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f/metal-gardener_persistence_prod_readonly_secureboot-amd64-1592.6-cb05e11f.raw
    metal-gardener_persistence_prod_readonly_secureboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f/metal-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f/metal-gardener_persistence_prod_readonly_secureboot-arm64-1592.6-cb05e11f.raw
    metal-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod-amd64-1592.6-cb05e11f/metal-gardener_prod-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod-amd64-1592.6-cb05e11f/metal-gardener_prod-amd64-1592.6-cb05e11f.raw
    metal-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod-arm64-1592.6-cb05e11f/metal-gardener_prod-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod-arm64-1592.6-cb05e11f/metal-gardener_prod-arm64-1592.6-cb05e11f.raw
    metal-gardener_prod_pxe-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_pxe-amd64-1592.6-cb05e11f/metal-gardener_prod_pxe-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_pxe-amd64-1592.6-cb05e11f/metal-gardener_prod_pxe-amd64-1592.6-cb05e11f.raw
    metal-gardener_prod_pxe-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_pxe-arm64-1592.6-cb05e11f/metal-gardener_prod_pxe-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_pxe-arm64-1592.6-cb05e11f/metal-gardener_prod_pxe-arm64-1592.6-cb05e11f.raw
    metal-gardener_prod_readonly_secureboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f/metal-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f/metal-gardener_prod_readonly_secureboot-amd64-1592.6-cb05e11f.raw
    metal-gardener_prod_readonly_secureboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f/metal-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f/metal-gardener_prod_readonly_secureboot-arm64-1592.6-cb05e11f.raw
    metal-gardener_prod_secureboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_secureboot-amd64-1592.6-cb05e11f/metal-gardener_prod_secureboot-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_secureboot-amd64-1592.6-cb05e11f/metal-gardener_prod_secureboot-amd64-1592.6-cb05e11f.raw
    metal-gardener_prod_secureboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_secureboot-arm64-1592.6-cb05e11f/metal-gardener_prod_secureboot-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_secureboot-arm64-1592.6-cb05e11f/metal-gardener_prod_secureboot-arm64-1592.6-cb05e11f.raw
    openstack-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstack-gardener_prod-amd64-1592.6-cb05e11f/openstack-gardener_prod-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstack-gardener_prod-amd64-1592.6-cb05e11f/openstack-gardener_prod-amd64-1592.6-cb05e11f.qcow2
    openstack-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstack-gardener_prod-arm64-1592.6-cb05e11f/openstack-gardener_prod-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstack-gardener_prod-arm64-1592.6-cb05e11f/openstack-gardener_prod-arm64-1592.6-cb05e11f.qcow2
    openstackbaremetal-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstackbaremetal-gardener_prod-amd64-1592.6-cb05e11f/openstackbaremetal-gardener_prod-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstackbaremetal-gardener_prod-amd64-1592.6-cb05e11f/openstackbaremetal-gardener_prod-amd64-1592.6-cb05e11f.qcow2
    openstackbaremetal-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstackbaremetal-gardener_prod-arm64-1592.6-cb05e11f/openstackbaremetal-gardener_prod-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstackbaremetal-gardener_prod-arm64-1592.6-cb05e11f/openstackbaremetal-gardener_prod-arm64-1592.6-cb05e11f.qcow2
    vmware-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/vmware-gardener_prod-amd64-1592.6-cb05e11f/vmware-gardener_prod-amd64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/vmware-gardener_prod-amd64-1592.6-cb05e11f/vmware-gardener_prod-amd64-1592.6-cb05e11f.ova
    vmware-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/vmware-gardener_prod-arm64-1592.6-cb05e11f/vmware-gardener_prod-arm64-1592.6-cb05e11f.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/vmware-gardener_prod-arm64-1592.6-cb05e11f/vmware-gardener_prod-arm64-1592.6-cb05e11f.ova
  oci: ghcr.io/gardenlinux/gardenlinux:1592.6
  attributes:
    source_repo: true
```
