### ISSUE TITLE
reactivate `flavours.yaml`

### ISSUE THREAD

**Issue by yeoldegrove** [gardenlinux/gardenlinux#2502]
**What would you like to be added**:

As shortly discussed in the daily, I would like to reactivate the [`flavours.yaml`](https://github.com/gardenlinux/gardenlinux/blob/eb1faaab86bcb370ab052972aeba385a8d3b54d0/flavours.yaml) file and use it as input for all our github actions and `Makefiles` to define which things to build and test.

**Why is this needed**:

Currently we define our flavours in several places and this tends to diverge.

**Things to notice**:

We also have a [`flavours.yaml`](https://github.com/gardenlinux/glci/blob/485b672ca428183287cfe097609be355e36be6d8/flavours.yaml) in the glci repo. This needs/should be synced eventually.

**Comment by yeoldegrove** [comment]
I would suggest that we extend the `flavors.yaml` like this:

```
  - name: aws
    category: public-cloud
    flavors:
      - modifier: gardener_prod
        features: []
        arch: amd64
        build: true
        test: true
        test-platform: true
        publish: true
      - modifier: gardener_prod
        features: []
        arch: arm64
        build: true
        test: true
        test-platform: true
        publish: true
      - modifier: gardener_prod
        features:
          - _trustedboot
        arch: amd64
        build: true
        test: true
        test-platform: true
        publish: false
      - modifier: gardener_prod
        features:
          - _trustedboot
        arch: arm64
        build: true
        test: true
        test-platform: true
        publish: false
      - modifier: gardener_prod
        features:
          - _trustedboot
          - _tpm2
        arch: amd64
        build: true
        test: true
        test-platform: true
        publish: true
      - modifier: gardener_prod
        features:
          - _trustedboot
          - _tpm2
        arch: arm64
        build: true
        test: true
        test-platform: true
        publish: true
   ```

This would enable us to do a lot more filtering for the build/test/publish scenarios that we have.
A small helper script could enable this:

```
# only get AWS flavors that are to be build
❯ bin/flavors_parse.py --include-only 'aws-*' --build
aws-gardener_prod-amd64
aws-gardener_prod-arm64
aws-gardener_prod_trustedboot-amd64
aws-gardener_prod_trustedboot-arm64
aws-gardener_prod_trustedboot_tpm2-amd64
aws-gardener_prod_trustedboot_tpm2-arm64

# only get AWS flavors on which platform-tests shall be run
❯ bin/flavors_parse.py --include-only 'aws-*' --test-platform
aws-gardener_prod-amd64
aws-gardener_prod-arm64
aws-gardener_prod_trustedboot-amd64
aws-gardener_prod_trustedboot-arm64
aws-gardener_prod_trustedboot_tpm2-amd64
aws-gardener_prod_trustedboot_tpm2-arm64

# only get AWS flavors that are to be published
❯ bin/flavors_parse.py --include-only 'aws-*' --publish
aws-gardener_prod-amd64
aws-gardener_prod-arm64
aws-gardener_prod_trustedboot_tpm2-amd64
aws-gardener_prod_trustedboot_tpm2-arm64
```

The flavors can also be fed to github actions (needs json for complex structures) with this new format.

```
❯ bin/flavors_parse.py --no-arch --json-by-arch --test-platform
{
  "amd64": [
    "ali-gardener_prod",
    "aws-gardener_prod",
    "aws-gardener_prod_trustedboot",
    "aws-gardener_prod_trustedboot_tpm2",
    "azure-gardener_prod",
    "azure-gardener_prod_trustedboot",
    "azure-gardener_prod_trustedboot_tpm2",
    "gcp-gardener_prod",
    "gcp-gardener_prod_trustedboot",
    "gcp-gardener_prod_trustedboot_tpm2"
  ],
  "arm64": [
    "ali-gardener_prod",
    "aws-gardener_prod",
    "aws-gardener_prod_trustedboot",
    "aws-gardener_prod_trustedboot_tpm2",
    "azure-gardener_prod",
    "azure-gardener_prod_trustedboot",
    "azure-gardener_prod_trustedboot_tpm2",
    "gcp-gardener_prod",
    "gcp-gardener_prod_trustedboot",
    "gcp-gardener_prod_trustedboot_tpm2"
  ]
}
```

```
# workflow.yaml
jobs:
  matrix:
    name: generate matrices
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
      - id: matrix
        run: |
          FLAVORS_AMD64=$(./bin/flavors_parse.py --no-arch --json-by-arch --test-platform | jq -r '.amd64')
          FLAVORS_ARM64=$(./bin/flavors_parse.py --no-arch --json-by-arch --test-platform | jq -r '.arm64')
          MATRIX=$(jq -nc \
            --argjson amd64 "$FLAVORS_AMD64" \
            --argjson arm64 "$FLAVORS_ARM64" \
            '{
              include: (
                ($amd64 | map({arch: "amd64", flavor: .})) +
                ($arm64 | map({arch: "arm64", flavor: .})) +
              )
            }'
          )
          echo "matrix=$MATRIX" | tee -a $GITHUB_OUTPUT

  platform_tests:
    name: platform test
    needs: [ matrix ]
...
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
...
```
