### ISSUE TITLE
Link release manifest files in glrd

### ISSUE THREAD

**Issue by MrBatschner** [gardenlinux/gardenlinux#2523]
**What would you like to be added**:

For every build/release that is uploaded to S3, we are creating a release manifest containing technical meta information and - especially - build artefact locations. It would be helpful is these were linked from glrd.

**Why is this needed**:

Easy access to Garden Linux build artefacts.

**Comment by yeoldegrove** [comment]
I like this idea as it makes it more transparent which flavors exist and where to download them for every release.

**Comment by yeoldegrove** [comment]
I would suggest adding a `flavors` column in the GLRD which holds information about all flavors that were officially built for a particular release. Information would initially be the `metadata` but also the actual `image` url would be nice in my opinion.
This would it make it easy later to query a release and get a download link to actually boot it.

Not sure if referencing GLCI objects could provide any value here. 

It could look like this for all flavors that are currently set to `publish` (uploaded to S3).

```
❯ bin/flavors_parse.py --publish
ali-gardener_prod-amd64
aws-gardener_prod-amd64
aws-gardener_prod-arm64
aws-gardener_prod_trustedboot_tpm2-amd64
aws-gardener_prod_trustedboot_tpm2-arm64
azure-gardener_prod-amd64
azure-gardener_prod-arm64
azure-gardener_prod_trustedboot_tpm2-amd64
azure-gardener_prod_trustedboot_tpm2-arm64
container-amd64
container-arm64
gcp-gardener_prod-amd64
gcp-gardener_prod-arm64
gcp-gardener_prod_trustedboot_tpm2-amd64
gcp-gardener_prod_trustedboot_tpm2-arm64
gdch-gardener_prod-amd64
gdch-gardener_prod-arm64
kvm-gardener_prod-amd64
kvm-gardener_prod-arm64
kvm-gardener_prod_trustedboot_tpm2-amd64
kvm-gardener_prod_trustedboot_tpm2-arm64
metal-gardener_prod-amd64
metal-gardener_prod-arm64
metal-gardener_prod_trustedboot_tpm2-amd64
metal-gardener_prod_trustedboot_tpm2-arm64
metal-vhost-amd64
metal-vhost-arm64
metal_pxe-amd64
metal_pxe-arm64
openstack-gardener_prod-amd64
openstack-gardener_prod-arm64
openstackbaremetal-gardener_prod-amd64
openstackbaremetal-gardener_prod-arm64
vmware-gardener_prod-amd64
vmware-gardener_prod-arm64
```

```
{
  "releases": [
    {
      "name": "nightly-1666.0",
      "type": "nightly",
      "version": {
        "major": 1666,
        "minor": 0
      },
      "lifecycle": {
        "released": {
          "isodate": "2024-10-22",
          "timestamp": 1729580400
        }
      },
      "git": {
        "commit": "98140d8449eda996c54f5a0f07bd18cdde2bc2a4",
        "commit_short": "98140d84"
      },
      "flavors": [
        "gcp-gardener_prod-amd64": {
          "metadata": "https://gardenlinux-github-releases.s3.amazonaws.com/meta/singles/gcp-gardener_prod-amd64-1666.0-98140d84",
          "image": "https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod-amd64-1666.0-98140d84/gcp-gardener_prod-amd64-1666.0-98140d84.gcpimage.tar.gz"
        },
        [...]
      ]
    }
  }
}
```

Our container flavors are currently called `bare-*` and not published on S3 but on ghcr.io.

```
❯ bin/flavors_parse.py --build --include-only "bare-*"
bare-libc-amd64
bare-libc-arm64
bare-nodejs-amd64
bare-nodejs-arm64
bare-python-amd64
bare-python-arm64
bare-sapmachine-amd64
bare-sapmachine-arm64
```

We could simply put the same values into `metadata` and `image` or come up with something else (no idea so far).

```
{
  "releases": [
    {
      "name": "nightly-1666.0",
      "type": "nightly",
      "version": {
        "major": 1666,
        "minor": 0
      },
      "lifecycle": {
        "released": {
          "isodate": "2024-10-22",
          "timestamp": 1729580400
        }
      },
      "git": {
        "commit": "98140d8449eda996c54f5a0f07bd18cdde2bc2a4",
        "commit_short": "98140d84"
      },
      "flavors": [
        "bare-sapmachine": {
          "metadata:" "ghcr.io/gardenlinux/gardenlinux/bare-sapmachine:1666.0",
          "image": "ghcr.io/gardenlinux/gardenlinux/bare-sapmachine:1666.0"
        }
        [...]
      ]
    }
  }
}
```

**Comment by yeoldegrove** [comment]
I thought a bit on how we could design the use cases:
- having a link to the OCI registry for each version (flavor independent)
- having all flavors that are existing for a release
- having S3 download links to flavor manifests and images
  
An additional goal is not having a lot of duplicated data in the GLRD schema.

This could be designed like this:
  - when creating a patch, nightly, dev release with `glrd-manage`
    - `flavors.yml` (from gardenlinux repo) for the specific commit is queried and parsed
    - "flavors" as a list of strings is added to the schema 
  - when querying a patch, nightly, dev release with `glrd`
    - shell-mode:
      - OCI can be queried
      - flavors are outputed as a list of strings
    - yaml/json-mode: flavors are outputed as a dict
      - `oci`: link to oci registry (flavor independent)
      - image/vm flavors:
        - `metadata:` url to S3 manifest
        - `image:` url to S3 image (based on platform)
      - container flavors:
        - `oci:` link to oci registry

GLRD schema:
```
    "nightly": {
        "type": "object",
        "properties": {
            "name": {"type": "string"},
            "type": {"enum": ["nightly"]},
            "version": {
                "type": "object",
                "properties": {"major": {"type": "integer"}, "minor": {"type": "integer"}},
                "required": ["major", "minor"]
            },
            "lifecycle": {
                "type": "object",
                "properties": {
                    "released": {"type": "object", "properties": {
                        "isodate": {"type": "string", "format": "date"},
                        "timestamp": {"type": "integer"}},
                        "required": ["isodate", "timestamp"]}
                },
                "required": ["released"]
            },
            "git": {
                "type": "object",
                "properties": {
                    "commit": {"type": "string", "pattern": "^[0-9a-f]{40}$"},
                    "commit_short": {"type": "string", "pattern": "^[0-9a-f]{7,8}$"}
                },
                "required": ["commit", "commit_short"]
            },
            "flavors": {
                "type": "array",
                "items": {"type": "string"}
            },
            "attributes": {
                "type": "object",
                "properties": {
                    "source_repo": {
                        "type": "boolean",
                        "default": True
                    }
                },
                "required": ["source_repo"]
            }
        },
        "required": ["name", "type", "version", "lifecycle", "git", "flavors"]
    },
```

`glrd` output:
```
releases:
- name: nightly-1771.0
  type: nightly
  version:
    major: 1771
    minor: 0
  lifecycle:
    released:
      isodate: '2025-02-11'
      timestamp: 1739280540
  git:
    commit: af53929e544fbd37026d7e87c0c1ecd03153f32e
    commit_short: af53929e
  flavors:
    ali-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/ali-gardener_prod-amd64-1771.0-af53929e/ali-gardener_prod-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/ali-gardener_prod-amd64-1771.0-af53929e/ali-gardener_prod-amd64-1771.0-af53929e.qcow2
    aws-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod-amd64-1771.0-af53929e/aws-gardener_prod-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod-amd64-1771.0-af53929e/aws-gardener_prod-amd64-1771.0-af53929e.raw
    aws-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod-arm64-1771.0-af53929e/aws-gardener_prod-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod-arm64-1771.0-af53929e/aws-gardener_prod-arm64-1771.0-af53929e.raw
    aws-gardener_prod_tpm2_trustedboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e/aws-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e/aws-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e.raw
    aws-gardener_prod_tpm2_trustedboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e/aws-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/aws-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e/aws-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e.raw
    azure-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod-amd64-1771.0-af53929e/azure-gardener_prod-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod-amd64-1771.0-af53929e/azure-gardener_prod-amd64-1771.0-af53929e.vhd
    azure-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod-arm64-1771.0-af53929e/azure-gardener_prod-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod-arm64-1771.0-af53929e/azure-gardener_prod-arm64-1771.0-af53929e.vhd
    azure-gardener_prod_tpm2_trustedboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e/azure-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e/azure-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e.vhd
    azure-gardener_prod_tpm2_trustedboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e/azure-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/azure-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e/azure-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e.vhd
    gcp-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod-amd64-1771.0-af53929e/gcp-gardener_prod-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod-amd64-1771.0-af53929e/gcp-gardener_prod-amd64-1771.0-af53929e.gcpimage.tar.gz
    gcp-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod-arm64-1771.0-af53929e/gcp-gardener_prod-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod-arm64-1771.0-af53929e/gcp-gardener_prod-arm64-1771.0-af53929e.gcpimage.tar.gz
    gcp-gardener_prod_tpm2_trustedboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e/gcp-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e/gcp-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e.gcpimage.tar.gz
    gcp-gardener_prod_tpm2_trustedboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e/gcp-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gcp-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e/gcp-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e.gcpimage.tar.gz
    gdch-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gdch-gardener_prod-amd64-1771.0-af53929e/gdch-gardener_prod-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gdch-gardener_prod-amd64-1771.0-af53929e/gdch-gardener_prod-amd64-1771.0-af53929e.gcpimage.tar.gz
    gdch-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gdch-gardener_prod-arm64-1771.0-af53929e/gdch-gardener_prod-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/gdch-gardener_prod-arm64-1771.0-af53929e/gdch-gardener_prod-arm64-1771.0-af53929e.gcpimage.tar.gz
    kvm-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod-amd64-1771.0-af53929e/kvm-gardener_prod-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod-amd64-1771.0-af53929e/kvm-gardener_prod-amd64-1771.0-af53929e.raw
    kvm-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod-arm64-1771.0-af53929e/kvm-gardener_prod-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod-arm64-1771.0-af53929e/kvm-gardener_prod-arm64-1771.0-af53929e.raw
    kvm-gardener_prod_tpm2_trustedboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e/kvm-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e/kvm-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e.raw
    kvm-gardener_prod_tpm2_trustedboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e/kvm-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/kvm-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e/kvm-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e.raw
    metal-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod-amd64-1771.0-af53929e/metal-gardener_prod-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod-amd64-1771.0-af53929e/metal-gardener_prod-amd64-1771.0-af53929e.raw
    metal-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod-arm64-1771.0-af53929e/metal-gardener_prod-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod-arm64-1771.0-af53929e/metal-gardener_prod-arm64-1771.0-af53929e.raw
    metal-gardener_prod_tpm2_trustedboot-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e/metal-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e/metal-gardener_prod_tpm2_trustedboot-amd64-1771.0-af53929e.raw
    metal-gardener_prod_tpm2_trustedboot-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e/metal-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e/metal-gardener_prod_tpm2_trustedboot-arm64-1771.0-af53929e.raw
    metal-vhost-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-vhost-amd64-1771.0-af53929e/metal-vhost-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-vhost-amd64-1771.0-af53929e/metal-vhost-amd64-1771.0-af53929e.raw
    metal-vhost-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-vhost-arm64-1771.0-af53929e/metal-vhost-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal-vhost-arm64-1771.0-af53929e/metal-vhost-arm64-1771.0-af53929e.raw
    metal_pxe-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal_pxe-amd64-1771.0-af53929e/metal_pxe-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal_pxe-amd64-1771.0-af53929e/metal_pxe-amd64-1771.0-af53929e.raw
    metal_pxe-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal_pxe-arm64-1771.0-af53929e/metal_pxe-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/metal_pxe-arm64-1771.0-af53929e/metal_pxe-arm64-1771.0-af53929e.raw
    openstack-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstack-gardener_prod-amd64-1771.0-af53929e/openstack-gardener_prod-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstack-gardener_prod-amd64-1771.0-af53929e/openstack-gardener_prod-amd64-1771.0-af53929e.qcow2
    openstack-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstack-gardener_prod-arm64-1771.0-af53929e/openstack-gardener_prod-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstack-gardener_prod-arm64-1771.0-af53929e/openstack-gardener_prod-arm64-1771.0-af53929e.qcow2
    openstackbaremetal-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstackbaremetal-gardener_prod-amd64-1771.0-af53929e/openstackbaremetal-gardener_prod-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstackbaremetal-gardener_prod-amd64-1771.0-af53929e/openstackbaremetal-gardener_prod-amd64-1771.0-af53929e.qcow2
    openstackbaremetal-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstackbaremetal-gardener_prod-arm64-1771.0-af53929e/openstackbaremetal-gardener_prod-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/openstackbaremetal-gardener_prod-arm64-1771.0-af53929e/openstackbaremetal-gardener_prod-arm64-1771.0-af53929e.qcow2
    vmware-gardener_prod-amd64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/vmware-gardener_prod-amd64-1771.0-af53929e/vmware-gardener_prod-amd64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/vmware-gardener_prod-amd64-1771.0-af53929e/vmware-gardener_prod-amd64-1771.0-af53929e.ova
    vmware-gardener_prod-arm64:
      metadata: https://gardenlinux-github-releases.s3.amazonaws.com/objects/vmware-gardener_prod-arm64-1771.0-af53929e/vmware-gardener_prod-arm64-1771.0-af53929e.manifest
      image: https://gardenlinux-github-releases.s3.amazonaws.com/objects/vmware-gardener_prod-arm64-1771.0-af53929e/vmware-gardener_prod-arm64-1771.0-af53929e.ova
    bare-libc-amd64:
      oci: ghcr.io/gardenlinux/gardenlinux/bare-libc:1771.0
    bare-libc-arm64:
      oci: ghcr.io/gardenlinux/gardenlinux/bare-libc:1771.0
    bare-nodejs-amd64:
      oci: ghcr.io/gardenlinux/gardenlinux/bare-nodejs:1771.0
    bare-nodejs-arm64:
      oci: ghcr.io/gardenlinux/gardenlinux/bare-nodejs:1771.0
    bare-python-amd64:
      oci: ghcr.io/gardenlinux/gardenlinux/bare-python:1771.0
    bare-python-arm64:
      oci: ghcr.io/gardenlinux/gardenlinux/bare-python:1771.0
    bare-sapmachine-amd64:
      oci: ghcr.io/gardenlinux/gardenlinux/bare-sapmachine:1771.0
    bare-sapmachine-arm64:
      oci: ghcr.io/gardenlinux/gardenlinux/bare-sapmachine:1771.0
    container-amd64:
      oci: ghcr.io/gardenlinux/gardenlinux:1771.0
    container-arm64:
      oci: ghcr.io/gardenlinux/gardenlinux:1771.0
  oci: ghcr.io/gardenlinux/gardenlinux:1771.0
  attributes:
    source_repo: true
```
