### ISSUE TITLE
Wrap OIDC workflow into an action?

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#3007]
For the CI/CD setup to update container images in my cluster for GLVD, I do those things in multiple workflows:

```yaml
      - name: Get OIDC token
        id: get-token
        run: |
          IDTOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=foo" | jq -r '.value')
          echo "idToken=${IDTOKEN}" >> $GITHUB_OUTPUT

      - uses: azure/k8s-set-context@v4
        with:
           method: kubeconfig
           kubeconfig: "${{ secrets.KUBECONFIG }}"
```

This is not super nice because the get-token step is a bit obscure, and also the audience might need to be changed depending on the cluster setup, so I was wondering if it would make sense to wrap this functionality in a separate action.

This would not really fit into the Gardenlinux org imo, so maybe this would make sense in the gardener org instead?

I imagine something like this:

```yaml
      - uses: gardener/authenticate@main
        with:
           kubeconfig: "${{ secrets.KUBECONFIG }}"
           audience: foo
```

This should return the token to use in the same way the 'Get OIDC token' step does.
